import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Common Scents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Common Scents!</h1>

        <p className={styles.description}>This is a work in progress.</p>
      </main>

      <footer className={styles.footer}>
        <div>Footer goes here</div>
      </footer>
    </div>
  );
};

export default Home;
