import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

import styles from '../styles/page.module.scss';

const Home: NextPage = () => {
  // useEffect(() => {
  //   fetch(new URL(`${serverUrl}/scents`).toString(), {
  //     headers: { 'Access-Control-Allow-Origin': '*' },
  //   })
  //     .then(async (res) => {
  //       const result = await res.json();
  //       if (Object.keys(result).includes('error')) {
  //         setError(error);
  //         return;
  //       }
  //     })
  //     .catch((err) => {
  //       console.error(err);
  //     });
  // }, [error]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Common Scents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Common Scents!</h1>

        <p className={styles.description}>This is a work in progress.</p>
      </main>

      <footer className={styles.footer}>
        <div>Footer goes here</div>
      </footer>
    </div>
  );
};

export default Home;
